import type { TarotCard } from "@/types/tarot";

export const majorArcana: TarotCard[] = [
  {
    id: 0,
    name: "The Fool",
    nameCn: "愚者",
    arcana: "major",
    meaningUp: ["新的开始", "勇气", "冒险", "自由"],
    meaningReversed: ["冲动", "轻率", "方向感不足", "逃避现实"],
  },
  {
    id: 1,
    name: "The Magician",
    nameCn: "魔术师",
    arcana: "major",
    meaningUp: ["行动力", "创造力", "掌控资源", "自信"],
    meaningReversed: ["操控", "自我怀疑", "虚张声势", "能量分散"],
  },
  {
    id: 2,
    name: "The High Priestess",
    nameCn: "女祭司",
    arcana: "major",
    meaningUp: ["直觉", "洞察", "神秘", "内在智慧"],
    meaningReversed: ["压抑直觉", "困惑", "隐藏信息", "情绪封闭"],
  },
  {
    id: 3,
    name: "The Empress",
    nameCn: "皇后",
    arcana: "major",
    meaningUp: ["丰盛", "滋养", "温柔", "成长"],
    meaningReversed: ["依赖", "过度付出", "停滞", "情绪化"],
  },
  {
    id: 4,
    name: "The Emperor",
    nameCn: "皇帝",
    arcana: "major",
    meaningUp: ["秩序", "责任", "稳定", "领导力"],
    meaningReversed: ["控制欲", "僵化", "压迫", "缺乏弹性"],
  },
  {
    id: 5,
    name: "The Hierophant",
    nameCn: "教皇",
    arcana: "major",
    meaningUp: ["传统", "规则", "学习", "信念"],
    meaningReversed: ["抗拒规则", "盲从", "价值冲突", "形式主义"],
  },
  {
    id: 6,
    name: "The Lovers",
    nameCn: "恋人",
    arcana: "major",
    meaningUp: ["关系", "选择", "契合", "真诚"],
    meaningReversed: ["犹豫", "关系失衡", "价值观不合", "逃避承诺"],
  },
  {
    id: 7,
    name: "The Chariot",
    nameCn: "战车",
    arcana: "major",
    meaningUp: ["推进", "意志力", "胜利", "目标明确"],
    meaningReversed: ["失控", "阻碍", "急躁", "方向偏移"],
  },
  {
    id: 8,
    name: "Strength",
    nameCn: "力量",
    arcana: "major",
    meaningUp: ["温柔的力量", "耐心", "勇敢", "自我掌控"],
    meaningReversed: ["焦虑", "自我怀疑", "失去耐心", "情绪波动"],
  },
  {
    id: 9,
    name: "The Hermit",
    nameCn: "隐者",
    arcana: "major",
    meaningUp: ["独处", "反思", "寻找答案", "沉淀"],
    meaningReversed: ["孤立", "逃避", "封闭", "过度退缩"],
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameCn: "命运之轮",
    arcana: "major",
    meaningUp: ["转机", "变化", "机会", "命运流动"],
    meaningReversed: ["停滞", "反复", "失去节奏", "时机未到"],
  },
  {
    id: 11,
    name: "Justice",
    nameCn: "正义",
    arcana: "major",
    meaningUp: ["公平", "理性", "责任", "结果显现"],
    meaningReversed: ["失衡", "偏见", "逃避责任", "判断失准"],
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameCn: "倒吊人",
    arcana: "major",
    meaningUp: ["暂停", "换角度", "等待", "觉察"],
    meaningReversed: ["拖延", "僵持", "无谓牺牲", "不愿放手"],
  },
  {
    id: 13,
    name: "Death",
    nameCn: "死神",
    arcana: "major",
    meaningUp: ["结束", "蜕变", "更新", "断舍离"],
    meaningReversed: ["抗拒改变", "停在过去", "无法放下", "消耗"],
  },
  {
    id: 14,
    name: "Temperance",
    nameCn: "节制",
    arcana: "major",
    meaningUp: ["平衡", "疗愈", "融合", "循序渐进"],
    meaningReversed: ["失衡", "过度", "节奏紊乱", "不协调"],
  },
  {
    id: 15,
    name: "The Devil",
    nameCn: "恶魔",
    arcana: "major",
    meaningUp: ["欲望", "束缚", "沉迷", "执念"],
    meaningReversed: ["挣脱束缚", "觉醒", "看清问题", "慢慢脱离"],
  },
  {
    id: 16,
    name: "The Tower",
    nameCn: "高塔",
    arcana: "major",
    meaningUp: ["突变", "打破旧结构", "真相显现", "重建"],
    meaningReversed: ["延迟爆发", "内在震荡", "害怕变化", "勉强维持"],
  },
  {
    id: 17,
    name: "The Star",
    nameCn: "星星",
    arcana: "major",
    meaningUp: ["希望", "疗愈", "信心", "愿景"],
    meaningReversed: ["迷茫", "失望", "信念不足", "情绪低落"],
  },
  {
    id: 18,
    name: "The Moon",
    nameCn: "月亮",
    arcana: "major",
    meaningUp: ["潜意识", "不确定", "情绪", "直觉波动"],
    meaningReversed: ["看清迷雾", "真相浮现", "焦虑缓解", "误会减少"],
  },
  {
    id: 19,
    name: "The Sun",
    nameCn: "太阳",
    arcana: "major",
    meaningUp: ["喜悦", "成功", "清晰", "能量提升"],
    meaningReversed: ["短暂低落", "延迟成果", "过度乐观", "表现受阻"],
  },
  {
    id: 20,
    name: "Judgement",
    nameCn: "审判",
    arcana: "major",
    meaningUp: ["觉醒", "总结", "重新开始", "回应召唤"],
    meaningReversed: ["迟疑", "自责", "错过信号", "无法释怀"],
  },
  {
    id: 21,
    name: "The World",
    nameCn: "世界",
    arcana: "major",
    meaningUp: ["完成", "圆满", "整合", "进入新阶段"],
    meaningReversed: ["未完成", "循环未闭合", "拖尾", "差最后一步"],
  },
];
